// Package field provides low-level functions and types for working with
// individual header fields. The primary tool for this is Field. This
// encapsulates a field twice. Once in a decoded, convenient human-readable form
// and (optionally) a second raw form, which is the fully encoded form. When
// headers are parsed, the original is preserved, but the field name and value
// will provide clean decoded values as much as possible.
//
// This package also provides the tools for folding and unfolding header fields
// and dealing with message line breaks.
//
// The ParseLines() function of this package is able to break up the lines of a
// header into individual header field lines.
//
// Given a parsed header field line, the Parse() function will return a parsed
// and decoded original field that should safely round-trip, if not modified.
// Parsing is quite liberal and will accept and correctly parse many email
// messages that can be generated by well-known software vendors who routinely
// violated RFCs when generating messages.
package field
