---
on:
  push:

jobs:
  readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - uses: actions/checkout@v3
      - run: go mod download
      - run: go install ./tools/pm
      - run: pm template-file docs/README.md.tmpl README.test.md
      - run: diff README.md README.test.md

  changelog-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - uses: actions/checkout@v3
      - run: go mod download
      - run: |
          if [[ "${GITHUB_REF:0:20}" == "refs/heads/release-v" ]]; then
            echo "LINT_CHANGELOG_OPT=-r" >> "$GITHUB_ENV"
          else
            echo "LINT_CHANGELOG_OPT=-p" >> "$GITHUB_ENV"
          fi
      - run: go run ./tools/pm changelog lint "$LINT_CHANGELOG_OPT"

  golang-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - uses: actions/checkout@v3
      - run: go mod download
      - uses: golangci/golangci-lint-action@v3
        with:
          version: v1.50.1
